### PR TITLE
Added draggable property draggable=true/false

### PR DESCRIPTION
**Pull request by jiren**

### CODE REVIEW

**Comment by allenhwkim** [comment]
`draggable` is the reserved keyword of HTML. 
I think we need to pick other term.

**Comment by jiren** [comment]
Got it. I will update it.  'make-draggable', 'is-draggable' are in my mind. What do you suggest?

**Comment by allenhwkim** [comment]
`is-draggable` sounds good to me.

**Comment by jiren** [comment]
Updated code. Have a look.

**Pull request merged**
